/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodjassignment.scheduler;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Requestcancel extends javax.swing.JFrame {

    public Requestcancel() {
        initComponents();
        loadBookingData();
    }

    private void loadBookingData() {
        DefaultTableModel model = (DefaultTableModel) Aschedule.getModel(); // Aschedule is your JTable
        Request request = new Request("src\\\\oodjassignment\\\\database\\\\Booking.txt");

        try {
            // Load only records with "Request for cancel"
            request.readFileToTable(model);
            System.out.println("Booking data loaded successfully."); // Debugging: confirm successful load
        } catch (Exception ex) {
            System.out.println("Error loading booking data: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Aschedule = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        HA = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(102, 102, 102));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodjassignment/picture/logout.png"))); // NOI18N
        logout.setText("Back");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Aschedule.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Aschedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Hall Type", "Hall No.", "Prices", "Date", "Time", "Duration", "Status", "Remarks"
            }
        ));
        Aschedule.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(Aschedule);
        if (Aschedule.getColumnModel().getColumnCount() > 0) {
            Aschedule.getColumnModel().getColumn(0).setMinWidth(100);
            Aschedule.getColumnModel().getColumn(0).setPreferredWidth(100);
            Aschedule.getColumnModel().getColumn(0).setMaxWidth(100);
            Aschedule.getColumnModel().getColumn(1).setMinWidth(100);
            Aschedule.getColumnModel().getColumn(1).setPreferredWidth(100);
            Aschedule.getColumnModel().getColumn(1).setMaxWidth(100);
            Aschedule.getColumnModel().getColumn(2).setMinWidth(120);
            Aschedule.getColumnModel().getColumn(2).setPreferredWidth(120);
            Aschedule.getColumnModel().getColumn(2).setMaxWidth(120);
            Aschedule.getColumnModel().getColumn(3).setMinWidth(95);
            Aschedule.getColumnModel().getColumn(3).setPreferredWidth(95);
            Aschedule.getColumnModel().getColumn(3).setMaxWidth(95);
            Aschedule.getColumnModel().getColumn(4).setMinWidth(95);
            Aschedule.getColumnModel().getColumn(4).setPreferredWidth(95);
            Aschedule.getColumnModel().getColumn(4).setMaxWidth(95);
            Aschedule.getColumnModel().getColumn(5).setMinWidth(100);
            Aschedule.getColumnModel().getColumn(5).setPreferredWidth(100);
            Aschedule.getColumnModel().getColumn(5).setMaxWidth(100);
            Aschedule.getColumnModel().getColumn(6).setMinWidth(100);
            Aschedule.getColumnModel().getColumn(6).setPreferredWidth(100);
            Aschedule.getColumnModel().getColumn(6).setMaxWidth(100);
            Aschedule.getColumnModel().getColumn(7).setMinWidth(100);
            Aschedule.getColumnModel().getColumn(7).setPreferredWidth(100);
            Aschedule.getColumnModel().getColumn(7).setMaxWidth(100);
            Aschedule.getColumnModel().getColumn(8).setMinWidth(150);
            Aschedule.getColumnModel().getColumn(8).setPreferredWidth(150);
            Aschedule.getColumnModel().getColumn(8).setMaxWidth(150);
            Aschedule.getColumnModel().getColumn(9).setMinWidth(179);
            Aschedule.getColumnModel().getColumn(9).setPreferredWidth(179);
            Aschedule.getColumnModel().getColumn(9).setMaxWidth(179);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1140, 600));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Status :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        status.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approve", "Decline" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 130, -1));

        Save.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Save.setText("Update");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        HA.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        HA.setForeground(new java.awt.Color(102, 102, 102));
        HA.setText("Hall Availability");
        HA.setMaximumSize(new java.awt.Dimension(155, 39));
        HA.setMinimumSize(new java.awt.Dimension(155, 39));
        HA.setPreferredSize(new java.awt.Dimension(155, 39));
        HA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAActionPerformed(evt);
            }
        });
        getContentPane().add(HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodjassignment/picture/blue.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to return to the Homepage?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new schedulerhomepage().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed

    }//GEN-LAST:event_statusActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        DefaultTableModel model = (DefaultTableModel) Aschedule.getModel();
        int selectedRow = Aschedule.getSelectedRow(); // 获取当前选中的行

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }

// 获取表格中的 Booking ID 和新状态
        String bookingID = (String) model.getValueAt(selectedRow, 0); // 获取Booking ID (第0列)
        String newStatus = (String) status.getSelectedItem(); // 获取新的状态
        model.setValueAt(newStatus, selectedRow, 8); // 更新表格中的状态 (第8列)

// 进行文件更新
        try {
            // 定义文件路径
            File file = new File("src/oodjassignment/database/Booking.txt");

            // 读取现有文件内容
            BufferedReader br = new BufferedReader(new FileReader(file));
            StringBuilder fileContent = new StringBuilder();
            String line;

            // 循环读取文件中的每一行
            while ((line = br.readLine()) != null) {
                String[] fields = line.split("/"); // 假设字段是用 "/" 分割的

                if (fields[0].equals(bookingID)) { // 如果Booking ID匹配
                    // 更新第九个字段为新状态
                    fields[8] = newStatus; // 更新状态字段

                    // 将更新后的字段重新拼接成一行
                    String updatedLine = String.join("/", fields);
                    fileContent.append(updatedLine).append("\n"); // 将更新后的行写入
                } else {
                    // 将其他行保持原样
                    fileContent.append(line).append("\n");
                }
            }
            br.close();

            // 将修改后的内容写回文件
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            bw.write(fileContent.toString());
            bw.close();

            JOptionPane.showMessageDialog(this, "Status updated successfully.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + ex.getMessage());
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void HAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAActionPerformed
        setVisible(false);
        new Hall_availability_schedule().setVisible(true);
    }//GEN-LAST:event_HAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requestcancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requestcancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requestcancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requestcancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requestcancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Aschedule;
    private javax.swing.JButton HA;
    private javax.swing.JButton Save;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
