/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodjassignment.scheduler;

import javax.swing.JOptionPane;
import oodjassignment.Loginpage;

/**
 *
 * @author Acer
 */
public class schedulerhomepage extends javax.swing.JFrame {

    /**
     * Creates new form schedulerhomepage
     */
    public schedulerhomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        smallb = new javax.swing.JPanel();
        havailability = new javax.swing.JButton();
        hmaintenance = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(0, 137, 248));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodjassignment/picture/logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        welcome.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome back ");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        smallb.setBackground(new java.awt.Color(0, 137, 248));

        havailability.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        havailability.setText("Hall availability schedule");
        havailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                havailabilityActionPerformed(evt);
            }
        });

        hmaintenance.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        hmaintenance.setText("Hall maintenance schedule");
        hmaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmaintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout smallbLayout = new javax.swing.GroupLayout(smallb);
        smallb.setLayout(smallbLayout);
        smallbLayout.setHorizontalGroup(
            smallbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallbLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(havailability)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hmaintenance)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        smallbLayout.setVerticalGroup(
            smallbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallbLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(smallbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(havailability, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(smallb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 460, 180));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodjassignment/picture/blue.jpg"))); // NOI18N
        background.setText("jLabel2");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Loginpage().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void havailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_havailabilityActionPerformed
        setVisible(false);
        new Hall_availability_schedule().setVisible(true);
    }//GEN-LAST:event_havailabilityActionPerformed

    private void hmaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmaintenanceActionPerformed
        setVisible(false);
        new Hall_maintenance_schedule().setVisible(true);
    }//GEN-LAST:event_hmaintenanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(schedulerhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(schedulerhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(schedulerhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(schedulerhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new schedulerhomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton havailability;
    private javax.swing.JButton hmaintenance;
    private javax.swing.JButton logout;
    private javax.swing.JPanel smallb;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
